spring:
  application:
    name: learn-jvm

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.1.101:5432/learn-jvm

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    default-schema: public

logging:
  level:
    org:
      springframework: debug