spring:
  application:
    name: learn-jvm

  config:
    import: file:.env[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_DATABASE_NODE_PROD:postgres}
    password: ${PASSWORD_DATABASE_NODE_PROD:postgres}
    url: jdbc:postgresql://${IP_NODE_DATABASE_PROD:192.168.1.101}:${PORT_NODE_DATABASE_PROD:5432}/learn-jvm

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    default-schema: public

  messages:
    basename: messages/messages
    use-code-as-default-message: true
    encoding: UTF-8
    always-use-message-format: true
    locale-default: en

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework: info

management:
  endpoints.web.exposure.include: 'prometheus, health'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

app:
  names:
    search-field-name: search
    sort-name: sort
    size-name: size
    page-number-name: page