spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_DATABASE_NODE_DEV:postgres}
    password: ${PASSWORD_DATABASE_NODE_DEV:postgres}
    url: jdbc:postgresql://${IP_NODE_DATABASE_DEV:192.168.1.103}:${PORT_NODE_DATABASE_DEV:5432}/learn-jvm

logging:
  level:
    org:
      springframework: info

management:
  endpoints.web.exposure.include: 'prometheus, health'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true